"use client";

import { useState } from 'react';

export default function Home() {
  const [loading, setLoading] = useState(false);

  return (
    <main className="min-h-screen bg-gradient-to-b from-gray-50 to-gray-100 py-12 px-4">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            DependencyDashboard
          </h1>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.<br>[View this repository on the M...
          </p>
        </div>

        <div className="bg-white rounded-lg shadow-md p-8 mb-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4">
            Features
          </h2>
          <ul className="space-y-2 text-gray-600">

          </ul>
        </div>

        <div className="bg-blue-50 rounded-lg p-6 text-center">
          <p className="text-blue-800">
            MVP generated by BabsXBT
          </p>
          <p className="text-sm text-blue-600 mt-2">
            Validation Score: 70/100
          </p>
        </div>
      </div>
    </main>
  );
}
